# Header
menu:
  Home: /
  Linux: /categories/linux
  Ansible: /categories/ansible
  Python: /categories/python
  Network: /categories/network
  Tools: /categories/tools
  Archives: /archives

rss: /atom.xml
banner: "images/banner.jpg"

# Content
excerpt_link: Read More
fancybox: true
recent_posts_limits: 5

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
- category
- tagcloud
- archive

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /images/favicon.png
twitter:
fb_admins:
fb_app_id:

# valine comment system. https://valine.js.org
valine:
  enable: true # if you want use valine,please set this value is true
  appId: p2FrmVMxcfWemqnNtET5iplC-gzGzoHsz # leancloud application app id
  appKey: 95bACKJlEpr1YLgRGMeRKVIt  # leancloud application app key
  notify: false # valine mail notify (true/false) https://github.com/xCss/Valine/wiki
  verify: false # valine verify code (true/false)
  pageSize: 10 # comment list page size
  avatar: mm # gravatar style https://valine.js.org/#/avatar
  lang: zh-cn # i18n: zh-cn/en
  placeholder: Just go go # valine comment input placeholder(like: Please leave your footprints )
  guest_info: nick,mail,link #valine comment header info
  visitor: true

#add by myself, there is no this configuration by default
post_copyright:
  enable: true 
  author: 李欢欢(robin h h li) 
  copyright_text: 作者拥有版权，请注明出处转载

#add by myself, there is no this configuration by default
donate:
  donate: true 
  donate_text: 如果喜欢我，可以请我喝咖啡哟!  也可以关注我的微信订阅号devops186
  alipay: /images/alipay.png
  wechat: /images/webchat.png